# Site settings
title: Emanuel Jankvist
email: immanuelpkj@protonmail.com
description: >-
  Personal website
baseurl: ""
url: ""

# Social links
social:
  github: EmanuelJankvist
  goodreads: emanueljankvist
  linkedin: emanuel-philip-konrad-jankvist-4b0791289
  twitter: immanuelpkj
  lesswrong: immanuelpkj
  # Uncomment below to activate arXiv link:
  # arxiv: https://arxiv.org/a/your_id.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
